import '../styles/globals.css';
import 'react-datepicker/dist/react-datepicker.css';
import styles from '../styles/Home.module.css';
import { useEffect } from 'react';
import type { AppProps } from 'next/app';
import { Provider } from 'react-redux';
import Head from 'next/head';

import { store } from '../store';
import { getNearContract } from '../utils';
import { setEventStatus } from '../store/reducers/contractReducer/actions';
// import { setAppStateDevMode } from '../store/reducers/appStateReducer/actions';
import { getUserAccountData } from '../store/reducers/userAccountReducer/actions';

import { mockUserAccount } from '../mockData/mockUserAccount';

import Header from '../components/header';

function MyApp({ Component, pageProps }: AppProps) {
  const initVselfWebApp = async () => {
    const { contract } = await getNearContract();
    const eventStatus = await contract.is_active();
    store.dispatch(setEventStatus(eventStatus));
    store.dispatch(getUserAccountData(mockUserAccount));
  };

  useEffect(() => {
    initVselfWebApp();
  }, []);

  return (
    <Provider store={store}>
      <Head>
        <title>VSELF APP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className={styles.container}>
        <Component {...pageProps} />
      </div>
    </Provider>
  );
}
export default MyApp;
