// import { useState, useEffect } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
// import Image from 'next/image';
import styles from '../styles/Home.module.css';

import { getState } from '../utils';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>VSELF APP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="xl flex-1">
        <button className="w-150px px-0.5 bg-gray-500" onClick={getState}>
          Get NEAR State
        </button>
      </div>
    </div>
  );
};

export default Home;
