// import { useState, useEffect } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Header from '../components/header';
import StartEventButton from '../components/startEventButton';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>VSELF APP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <StartEventButton />
    </div>
  );
};

export default Home;
