name: Deploy Web App to Firebase Hosting
'on':
  push:
    branches:
      - staging
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node Modules And Build App
        run: npm i && npm ci && npm run build:prod && sudo npm i -g firebase-tools
      - name: Deploy Web App to Staging
        if: github.ref == 'refs/heads/staging'
        run: firebase deploy -P staging --only hosting,functions:nextServer --non-interactive --token ${{ secrets.FIREBASE_DEPLOY_TOKEN }} -m "RunID ${{ github.run_id }} Commit SHA ${{ github.sha }}"
      - name: Deploy Web App to Production
        if: github.ref == 'refs/heads/main'
        run: firebase deploy -P prod --only hosting,functions:nextServer --non-interactive --token ${{ secrets.FIREBASE_DEPLOY_TOKEN }} -m "RunID ${{ github.run_id }} Commit SHA ${{ github.sha }}"
